version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "@chakra-ui/react"
        versions: [">=3.0.0"]
